import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import cardStyles from '../styles/Card.module.css'
import Card from './cards/Card'
import {AnimateSharedLayout, motion} from 'framer-motion'
import OrionPage from './content/Orion'
import MainPage from './content/Main'
import JSPetsPage from './content/JSPets'
import MusicPlayerPage from './content/MusicPlayer'
import CheckInPage from './content/CheckIn'
import SocialButtons from './content/Socials'
import ReactGA from 'react-ga'
import {useEffect} from 'react'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTimes } from '@fortawesome/free-solid-svg-icons'

export default function Home() {
  useEffect(() => {
    ReactGA.initialize('UA-70003644-4');
    ReactGA.pageview(window.location.pathname);
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Joseph Tran's projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sword.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my website!
        </h1>

        <p className={styles.description}>
          My name is Joseph TRAN and I am a software engineer.
        </p>

        <SocialButtons />

        <div>
          <AnimateSharedLayout>
            <motion.div layout className={styles.grid}>
              <Card link="https://github.com/SquireOfSoftware"
                    title="Main Github page"
                    blurb="For seeing what I have done outside of work."
                    content={(<MainPage />)}
                    openCard={() => ReactGA.pageview(window.location.pathname + "#GithubPage")}/>

              <Card link="https://github.com/SquireOfSoftware/Orion"
                    title="Orion"
                    blurb="An Autonomous Drone Flight system. Aiming to make drone flight autonomous via just highlighting key checkpoints on an iPad"
                    content={(<OrionPage />)}
                    openCard={() => ReactGA.pageview(window.location.pathname + "#Drone")}/>

              <Card link="https://squireofsoftware.github.io/JSPets/"
                    title="JSPets"
                    blurb="A digital pet experience, walking around Tasmania"
                    content={(<JSPetsPage />)}
                    openCard={() => ReactGA.pageview(window.location.pathname + "#Drone")}/>

              <Card link="https://github.com/SquireOfSoftware/NNFL/tree/master/Project/"
                    title="Hand Gesture Music Player"
                    blurb="Controlling your music player via hand gestures in Matlab with a Neural Network behind it"
                    content={(<MusicPlayerPage />)}
                    openCard={() => ReactGA.pageview(window.location.pathname + "#NeuralNet")}/>

              <Card link="https://github.com/SquireOfSoftware/check-in"
                    title="Check in"
                    blurb="A sign in system to track the people who enter a church for the purposes of resource provisioning and forecasting for events and food"
                    content={(<CheckInPage />)}
                    openCard={() => ReactGA.pageview(window.location.pathname + "#CheckIn")}/>
            </motion.div>
          </AnimateSharedLayout>
        </div>

      </main>

      <footer className={styles.footer}>
        <SocialButtons />
      </footer>
    </div>
  )
}
